# Generated by Django 4.1.7 on 2023-03-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
